login:
  username: mmuster
  password: Y29ycmVjdCBob3JzZSBiYXR0ZXJ5IHN0YXBsZQ== # only if not in keystore?
  email: maria.muster@hsr.ch

sync:
  remotes: # available file servers
    skripte:
      hostname: 152.96.90.26
      port: 445
      share: skripte
      domain: HSR

  global_exclude:
    - .DS_Store
    - Thumbs.db

  repositories: # sync-units
    InfSi1:
      remote: skripte # file server to use
      remote_dir: Informatik/Fachbereich/Informationssicherheit_1_-_Grundlagen/InfSi1
      local_dir: synced/InfSi1
      exclude: 
        - *.exe
        - Archiv
