login:
  username: mmuster
  password: Y29ycmVjdCBob3JzZSBiYXR0ZXJ5IHN0YXBsZQ== # only if not in keystore?
  email: maria.muster@hsr.ch

sync:
  global_exclude:
    - .DS_Store
    - Thumbs.db

  conflict_handling:
    local-changes: keep # ask | keep | overwrite | addfiles
    remote-deleted: delete # delete | keep

  repositories: # sync-units
    InfSi1:
      remote_dir: Informatik/Fachbereich/Informationssicherheit_1_-_Grundlagen/InfSi1
      local_dir: synced/InfSi1
      exclude: 
        - '*.exe'
        - 'Archiv'
