login:
  username: mmuster
  email: maria.muster@hsr.ch

sync:
  global-exclude:
    - .DS_Store
    - Thumbs.db

  conflict-handling:
    local-changes: ask
    remote-deleted: ask
    
  default-local-dir: /path/to/your/files/<name>/  

  repositories:
    InfSi1:
      remote-dir: Informatik/Fachbereich/Informationssicherheit_1_-_Grundlagen/InfSi1
      exclude:
        - '*.exe'
        - 'Archiv'
